---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
        -
          image: "paasrepo.azurecr.io/paasrepo:release1.0"
          name: angular
          ports:
            -
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  ports:
    -
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: angular
  type: LoadBalancer
